<?php

/**
 * Implements hook_form_id_alter
 */
function alteration_form_search_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    $form['#action'] = '/search/jobs';
    $form['keys']['#attributes']['placeholder'] = t('Search for your next job...');
}

/**
 * Implements hook_form_id_alter
 */
function alteration_form_node_jobs_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    $form['field_company']['widget']['#options'] = '';
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    $userId = $user->get('uid')->value;

    $companyNids = db_select('node__field_company_representative', 'n')
       ->condition('n.field_company_representative_target_id', $userId, '=')
       ->fields('n', array('entity_id'))
       ->execute()->fetchAssoc();
    if($companyNids){
        foreach ($companyNids as $nid) {
            $company =  \Drupal\node\Entity\Node::load($nid);
            $companyArray[$nid] = $company->getTitle();
        }
        $form['field_company']['widget']['#options'] = $companyArray;
    }
}

/**
 * Implements hook_form_id_alter
 */
function alteration_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    $form['account']['mail']['#description'] = '';
    $form['company_rep'] = array(
        '#type' => 'checkbox',
        '#title' => t("I am Company Representative."),
        '#weight' => 6,
    );

    $form['actions']['submit']['#submit'][] = 'alteration_form_user_register_form_submit';
}

/**
* Implements hook_form_id_submit().
*/
function alteration_form_user_register_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state)
{
    $form_state->setRedirect('user.page');
}

/**
* Implements hook_block_view_alter().
*/
function alteration_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block)
{
    if ('apply_button_block' == $block->getBaseId()) {
        $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
        $userId = $user->get('uid')->value;

        $jobNode = \Drupal::routeMatch()->getParameter('node');
        $jobNodeId = $jobNode->id();

        $applicationDate = db_select('user_job_application', 'uja')
           ->condition('uja.job_id', $jobNodeId, '=')
           ->condition('uja.user_id', $userId, '=')
           ->fields('uja', array('date'))
           ->execute()->fetchField();

        if ($applicationDate) {
            $formattedDate = date('F jS Y', strtotime($applicationDate));
            $build = array(
                         '#markup' => "<span class='already-applied'>You already applied to this job on $formattedDate</span>",
                         '#cache' => array(
                             'max-age' => 0,
                         ),
                         '#configuration' => array(
                             'label' => ''
                         )
                     );
        }
    }
}

/**
* Implements hook_user_login().
*/
function alteration_user_login($account)
{
    $userRole = \Drupal::currentUser()->getRoles();
    if (in_array('company_representative', $userRole)) {
        $response = new Drupal\Core\Routing\TrustedRedirectResponse('/node/add/jobs');
        $response->send();
        return;
    }
}
